/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:eb9d5391-a5e9-46f1-8f02-0bcd314ff85e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_44mLZouhz",
    "aws_user_pools_web_client_id": "3ian895dtkkdtksvlkmva9s6iu",
    "oauth": {}
};


export default awsmobile;
